// If you set GOOGLE_SCRIPT_URL in your .env file or Vercel, it will use that.
// Otherwise, it falls back to this demo database.
export const GOOGLE_SCRIPT_URL = process.env.GOOGLE_SCRIPT_URL || "https://script.google.com/macros/s/AKfycbwFI-Kz4SBEn9l7M1czxQ1MXoztqhwZQ-MN4j7u9NmicZ0pUg00MN6-8-4cuHwuZl4uXQ/exec";

// Updated list with City Prefixes for major terminals to aid search
export const INDIAN_STATIONS = [
  "Agra Cantt (AGC)",
  "Agartala (AGTL)",
  "Agra Fort (AF)",
  "Ahmedabad Jn (ADI)",
  "Ahmednagar (ANG)",
  "Ajmer Jn (AII)",
  "Akola Jn (AK)",
  "Alappuzha (ALLP)",
  "Aligarh Jn (ALJN)",
  "Allahabad Jn (Prayagraj) (ALD)",
  "Alwar (AWR)",
  "Ambala Cantt (UMB)",
  "Amravati (AMI)",
  "Amritsar Jn (ASR)",
  "Anand Jn (ANND)",
  "Asansol Jn (ASN)",
  "Aurangabad (AWB)",
  "Ayodhya Cantt (AYC)",
  "Ayodhya Dham (AY)",
  "Azamgarh (AMH)",
  "Bangalore City (SBC)",
  "Bangalore Cantt (BNC)",
  "Bangalore East (BNCE)",
  "Bangalore Yesvantpur (YPR)",
  "Bareilly Jn (BE)",
  "Baroda (BRC)",
  "Beas (BEAS)",
  "Begampet (BMT)",
  "Belagavi (BGM)",
  "Bellary Jn (BAY)",
  "Bhatinda Jn (BTI)",
  "Bhopal Jn (BPL)",
  "Bhubaneswar (BBS)",
  "Bhuj (BHUJ)",
  "Bikaner Jn (BKN)",
  "Bilaspur Jn (BSP)",
  "Bina Jn (BINA)",
  "Bokaro Steel City (BKSC)",
  "Borivali (BVI)",
  "Chandigarh (CDG)",
  "Chengalpattu Jn (CGL)",
  "Chennai Central (MAS)",
  "Chennai Egmore (MS)",
  "Chennai Tambaram (TBM)",
  "Chhapra Jn (CPR)",
  "Chittoor (CTO)",
  "Coimbatore Jn (CBE)",
  "Cuttack (CTC)",
  "Darbhanga Jn (DBG)",
  "Davangere (DVG)",
  "Dehradun (DDN)",
  "Delhi Anand Vihar (ANVT)",
  "Delhi Cantt (DEC)",
  "Delhi Hazrat Nizamuddin (NZM)",
  "Delhi Sarai Rohilla (DEE)",
  "Dhanbad Jn (DHN)",
  "Dharwad (DWR)",
  "Durg (DURG)",
  "Durgapur (DGR)",
  "Ernakulam Jn (ERS)",
  "Ernakulam Town (ERN)",
  "Erode Jn (ED)",
  "Faridabad (FDB)",
  "Firozpur Cantt (FZR)",
  "Gandhidham Jn (GIMB)",
  "Gandhinagar Jaipur (GADJ)",
  "Gandhinagar Capital (GNC)",
  "Gaya Jn (GAYA)",
  "Ghaziabad (GZB)",
  "Goa Madgaon (MAO)",
  "Gorakhpur Jn (GKP)",
  "Gulbarga (KLBG)",
  "Guntur Jn (GNT)",
  "Gurgaon (GGN)",
  "Guwahati (GHY)",
  "Gwalior (GWL)",
  "Haldwani (HDW)",
  "Haridwar (HW)",
  "Hubli Jn (UBL)",
  "Hyderabad Deccan (HYB)",
  "Hyderabad Kacheguda (KCG)",
  "Hyderabad Lingampalli (LPI)",
  "Hyderabad Secunderabad (SC)",
  "Indore Jn (INDB)",
  "Itarsi Jn (ET)",
  "Jabalpur (JBP)",
  "Jaipur (JP)",
  "Jalandhar City (JUC)",
  "Jalandhar Cantt (JRC)",
  "Jammu Tawi (JAT)",
  "Jamnagar (JAM)",
  "Jamshedpur (TATA)",
  "Jhansi Jn (VGLJ)",
  "Jodhpur Jn (JU)",
  "Kakinada Town (CCT)",
  "Kalka (KLK)",
  "Kalyan Jn (KYN)",
  "Kannur (CAN)",
  "Kanpur Central (CNB)",
  "Kanyakumari (CAPE)",
  "Karnal (KUN)",
  "Karwar (KAWR)",
  "Katpadi Jn (KPD)",
  "Kharagpur Jn (KGP)",
  "Kochi (ERS)",
  "Kolhapur (KOP)",
  "Kolkata Howrah Jn (HWH)",
  "Kolkata Sealdah (SDAH)",
  "Kolkata Shalimar (SHM)",
  "Kolkata (KOAA)",
  "Kollam Jn (QLN)",
  "Kota Jn (KOTA)",
  "Kottayam (KTYM)",
  "Kozhikode (CLT)",
  "Kurnool City (KRNT)",
  "Kurukshetra Jn (KKDE)",
  "Lucknow Charbagh (LKO)",
  "Lucknow Jn (LJN)",
  "Ludhiana Jn (LDH)",
  "Madurai Jn (MDU)",
  "Malda Town (MLDT)",
  "Mangalore Central (MAQ)",
  "Mangalore Jn (MAJN)",
  "Mathura Jn (MTJ)",
  "Meerut City (MTC)",
  "Moradabad (MB)",
  "Mumbai Bandra Terminus (BDTS)",
  "Mumbai Central (MMCT)",
  "Mumbai CSMT (Chhatrapati Shivaji Maharaj Terminus)",
  "Mumbai Dadar Central (DR)",
  "Mumbai Dadar Western (DDR)",
  "Mumbai LTT (Lokmanya Tilak Terminus)",
  "Muzaffarpur Jn (MFP)",
  "Mysore Jn (MYS)",
  "Nadiad Jn (ND)",
  "Nagpur (NGP)",
  "Nashik Road (NK)",
  "Nellore (NLR)",
  "New Delhi (NDLS)",
  "New Jalpaiguri (NJP)",
  "Nizamabad (NZB)",
  "Panaji (MAO)",
  "Panipat Jn (PNP)",
  "Panvel (PNVL)",
  "Pathankot (PTK)",
  "Patna Jn (PNBE)",
  "Pondicherry (PDY)",
  "Prayagraj Jn (PRYJ)",
  "Pune Jn (PUNE)",
  "Puri (PURI)",
  "Raipur Jn (R)",
  "Rajahmundry (RfY)",
  "Rajkot Jn (RJT)",
  "Rameswaram (RMM)",
  "Ranchi (RNC)",
  "Ratlam Jn (RTM)",
  "Renigunta Jn (RU)",
  "Rewa (REWA)",
  "Roorkee (RK)",
  "Rourkela (ROU)",
  "Salem Jn (SA)",
  "Sambalpur (SBP)",
  "Sangli (SLI)",
  "Satara (STR)",
  "Shimla (SML)",
  "Shirdi Sai Nagar (SNSI)",
  "Siliguri Jn (SGUJ)",
  "Solapur (SUR)",
  "Srinagar (SINA)",
  "Surat (ST)",
  "Thane (TNA)",
  "Thanjavur (TJ)",
  "Thiruvananthapuram Central (TVC)",
  "Tiruchchirappalli Jn (TPJ)",
  "Tirunelveli Jn (TEN)",
  "Tirupati (TPTY)",
  "Trichy (TPJ)",
  "Udaipur City (UDZ)",
  "Udupi (UD)",
  "Ujjain Jn (UJN)",
  "Vadodara Jn (BRC)",
  "Valsad (BL)",
  "Varanasi Jn (BSB)",
  "Vasai Road (BSR)",
  "Vasco Da Gama (VSG)",
  "Vellore Cantt (VLR)",
  "Vijayawada Jn (BZA)",
  "Villupuram Jn (VM)",
  "Virar (VR)",
  "Visakhapatnam (VSKP)",
  "Vizianagaram Jn (VZM)",
  "Warangal (WL)",
];
